### ISSUE TITLE
List of articles with links

### ISSUE THREAD

**Issue by volodya-lombrozo** [mximp/papers-reading-club#1]
Maybe we will just keep single list with all articles in the README file?  Instead of pushing them as PDF.

For example: 
```
Effective Function Merging in the SSA form
Authors: Rodrigo C. O. Rocha, Pavlos Petoumenos, Zheng Wang, Murray Cole, and Hugh Leather.  (UK)
Keywords: Code Size Reduction, Function Merging, LTO. 

Proceedings of the 41st ACM SIGPLAN International Conference on Programming Language Design and Implementation (PLDI ’20), June 15ś20, 2020, London, UK. ACM, New York, NY, USA 
Link to the article: https://dl.acm.org/doi/10.1145/3385412.3386030
Link to the presentation: [save it to the repo and add link]
```

**Comment by volodya-lombrozo** [comment]
@mximp Then great! But I would keep some sort of common list maybe with all articles, to make it easier to search. By the way, what do you think about Github Pages?

**Comment by mximp** [comment]
> @mximp Then great! But I would keep some sort of common list, maybe, with all articles, to make it easier to search. By the way, what do you think about Github Pages?

That's interesting idea... but again need to think how to maintain will minimal effort.

**Comment by mximp** [comment]
@volodya-lombrozo since we have [this site](https://mximp.github.io/papers-reading-club/) in place can we close this task?
